apiVersion: v1
kind: Service
metadata:
  name: mutating-webhook
  labels:
    app: mutating-webhook
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: mutating-webhook